#!/usr/bin/env bash

SETUP_ERRORS=()

if [ -z "$DEPLOY_ENV" ]; then
  SETUP_ERRORS+="DEPLOY_ENV variable is required."
fi

if [ -z "$SITE_USER" ]; then
  SETUP_ERRORS+="SITE_USER variable is required."
fi

if [ -z "$GIT_REPO" ]; then
  SETUP_ERRORS+="GIT_REPO variable is required."
fi

if [ -z "$SITE_USER_RSA_PRIV_KEY_VALUE" ]; then
  SETUP_ERRORS+="SITE_USER_RSA_PRIV_KEY_VALUE variable is required."
fi

if [ -z "$SITE_USER_RSA_PUB_KEY_VALUE" ]; then
  SETUP_ERRORS+="SITE_USER_RSA_PUB_KEY_VALUE variable is required."
fi

if [ "${#SETUP_ERRORS[*]}" > 0 ]; then
  {
    for SETUP_ERROR in "${SETUP_ERRORS[@]}"
    do
      echo "$SETUP_ERROR"
    done
  } > "/var/log/install-script-errors.log" 2>&1
fi

HEADLESS=true
PROJECT_DIR="/app"
RELAY_DIR="/deploy-relay"
DOCKER_DIR="$PROJECT_DIR/docker"

APP_ENV=prod

if [ "$DEPLOY_ENV" == "dev" ]; then
  DEPLOY_BRANCH=main-edge
elif [ "$DEPLOY_ENV" == "prod" ]; then
  DEPLOY_BRANCH=main-stable
fi

export HEADLESS
export PROJECT_DIR
export RELAY_DIR
export DOCKER_DIR
export DEPLOY_ENV
export SITE_USER

bash <(wget -qO - https://raw.githubusercontent.com/jfdialogs/linode-scripts/install-site-user)

HAS_SITE_USER="$(getent passwd $SITE_USER)"

if [ -d "$PROJECT_DIR" ]; then
  rm -d "$PROJECT_DIR"
fi

if [ -d "$RELAY_DIR" ]; then
  rm -d "$RELAY_DIR"
fi

mkdir "$PROJECT_DIR"
mkdir "$RELAY_DIR"

chown -R "$SITE_USER" "$PROJECT_DIR"
chown -R "$SITE_USER" "$RELAY_DIR"
chgrp -R "$SITE_USER" "$PROJECT_DIR"
chgrp -R "$SITE_USER" "$RELAY_DIR"

git config --global http.postBuffer 524288000

su -c "git clone -b $DEPLOY_BRANCH $GIT_REPO $PROJECT_DIR" - "$SITE_USER"

#"$DOCKER_DIR/server" init-prod && echo ""
#"$DOCKER_DIR/server" install-hooks && echo ""
#"$DOCKER_DIR/server" own-project && echo ""
#"$DOCKER_DIR/server" setup-volume && echo ""
#
#cd "$PROJECT_DIR"
#
#source "$PROJECT_DIR/.env"
#source "$PROJECT_DIR/.env.prod"
#
#export PROD_DB_HOST
#export PROD_DB_PORT
#export PROD_DB_NAME
#export PROD_DB_USER
#export PROD_DB_PASSWORD
#
#ln -s "$PROJECT_DIR" /app
#chown www-data /app
#chgrp www-data /app
